backend:
  name: git-gateway
  branch: main # Your default Git branch
media_folder: static/images/uploads # Where images will be stored
public_folder: /images/uploads
collections:
  - name: blog
    label: Blog
    folder: content/blogs
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
